### PR TITLE
fix: correct saw wave generation for accurate waveform output

### PR DESCRIPTION
**Pull request by daniel-feldhaus**
This PR *should* correct the error with the make_saw function. I say "should" because I don't have a midi controller, but I did make some graphs and they look pretty good.
image

_P.S. Sorry for doing this during class._

### CODE REVIEW

**Review by BartMassey — CHANGES_REQUESTED** [review]
Thanks! Thought it would be something like this. (Working during class is *fine*.)

Just as an exercise, please try to cut the patch down to a minimal change: looks like it would be two lines, really. No whitespace patches, no restructuring. That makes it much easier for me to push the button.

Again, greatly appreciated!

**Comment by daniel-feldhaus** [comment]
Thanks for the feedback! Somehow it took eight more commits, but I've brought the change down to two lines.

**Review by BartMassey — APPROVED** [review]
Still extra whitespace :grinning: but close enough. Thanks much once again.

**Comment by BartMassey** [comment]
Thanks much!

**Pull request merged**
